name: Build and Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Copy frontend build to Python package
        run: |
          rm -rf llmtraceviewer/_frontend_out
          mkdir -p llmtraceviewer/_frontend_out
          cp -r frontend/out/* llmtraceviewer/_frontend_out/

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Upload dist/ as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/
